# Generated by Django 4.2 on 2025-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='clothes')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
