# Generated by Django 4.2 on 2025-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tags'),
        ),
    ]
