# Generated by Django 4.2 on 2025-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='img',
            field=models.ImageField(upload_to='media/clothes'),
        ),
    ]
