
FROM node:18-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /frontend

# Copia el archivo package.json y package-lock.json (o yarn.lock si usas Yarn)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente al contenedor
COPY . .

# Expone el puerto 80
EXPOSE 3000


# Inicia la aplicación
CMD ["npm", "start"]
