
FROM node:18 as build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (o yarn.lock si usas Yarn)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente al contenedor
COPY . .

# Compila la aplicación para producción
RUN npm run build

# Etapa 2: Servidor NGINX
FROM nginx:stable-alpine

# Copia los archivos estáticos generados al directorio por defecto de NGINX
COPY --from=build /app/build /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]