services:
    backend:
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app
        environment:
            - DEBUG=1
            - ALLOWED_HOSTS=localhost,127.0.0.1
        command: >
            sh -c "python manage.py makemigrations --noinput &&
                    python manage.py migrate --noinput &&
                    python manage.py runserver 0.0.0.0:8000"
    frontend:
        ports:
            - "3000:3000"
        volumes:
            - ./app/node_modules
        stdin_open: true
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm start"
