# Generated by Django 4.2 on 2025-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
    ]
