# Generated by Django 4.2 on 2025-02-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPlanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit')),
            ],
        ),
    ]
