# Generated by Django 4.2 on 2025-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit_planner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('date', models.DateField()),
                ('outfit', models.IntegerField()),
            ],
        ),
    ]
