# Generated by Django 4.2 on 2025-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('user', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
