# Generated by Django 4.2 on 2025-01-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_clothes_tags_alter_clothes_user_clothes_tags'),
        ('tags', '0001_initial'),
        ('user', '0001_initial'),
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='Garments',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='tags',
        ),
        migrations.AlterField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='Garments',
            field=models.ManyToManyField(blank=True, to='clothes.clothes'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tags'),
        ),
    ]
