# Generated by Django 4.2 on 2025-02-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='img',
            field=models.ImageField(blank=True, upload_to='outfit'),
        ),
    ]
